/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class javacode_javacode */

#ifndef _Included_javacode_javacode
#define _Included_javacode_javacode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     javacode_javacode
 * Method:    Work
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_javacode_javacode_Work
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
